
=== 2023

link:/journal/2023/research_ssh_with_2fa/["Research on SSH with 2FA"^].
In this journal, we review several options to manage SSH authorization
beyond using public keys, possibly also enabling 2FA, using
https://tools.ietf.org/html/rfc6238[Time-Based One-Time Password^] (TOTP).
Some of the alternatives that we will review are Google Cloud OS Login,
Smallstep, Teleport, and google-authenticator-libpam.

link:/journal/2023/using_systemd_mkosi_2/["Using systemd mkosi for
development (round 2)"].
Continuing previous attempt, in this journal we take different path.

link:/journal/2023/using_systemd_mkosi/[Using systemd mkosi for
development].
In this journal, I will take a notes on my journey learning and using
mkosi as part of integration tests for developing
https://sr.ht/~shulhan/awwan[awwan^].
The goal is that when I run `make` on awwan repository, it will create
and run a container using systemd-nspawn(1) with SSH server running, and
run all tests inside the container.

link:/journal/2023/status_page_review/[Reviewing status page websites].
This journal review and dissecting several famous status page (or also known
as service health).

link:/journal/2023/replacing_postfix_with_opensmtpd/[Replacing Postfix with
OpenSmtpd^].
I have read several articles on OpenSMTPD and interested to use it.
In this article we describe the process to replace Postfix with OpenSMPTD.

link:/journal/2023/email_server_using_postfix_opendkim_dovecot/["Email
server using Postfix, OpenDKIM, and Dovecot"^].
This article describe my current email server configuration using Postfix,
OpenDKIM, and Dovecot.

link:/journal/2023/go2_error_handling/[Proposal for Go error handling^].

link:/journal/2023/type_and_variable_naming/[Better approach for type and
variable naming ^].
Naming variable is still hard, at some point.
In order to make it less hard, we can create barriers, to round naming
scopes, by applying several rules.

link:/journal/2023/go_test_data/[Go test.Data: helper for testing with large output^].

link:/journal/2023/2022_accomplishment/[2022 accomplishment^].

link:/journal/2023/trying_to_build_a_product/[Trying to build a product^].

link:/journal/2023/a_trip_to_labuan_bajo/[A trip to Labuan Bajo^].
