= Lesson from learning swimming
Shulhan <ms@kilabit.info>
22 Oct 2022
:toc:
:sectlinks:

One of my goal in 2022 is to be able to swim.
I started to learn since February 2022, once a week, with help from my wife
(which learn swim since young ages) and two tools, a hand paddles, a pull buoy
for leg, and obviously a goggles.

First, we learn the breaststroke technique.
After two-three months I can swim back and forth 100 meters, non-stop.
I am not reaching for speed but for survivability;
in case one day I am stranded in big water like ocean, at least I can try to
reach the nearest land without anyone help.

Once I feel confident with breaststroke, we move to the next technique:
freestyle swimming.
I thought swimming is likes cycling, once you know how to balance and move
forward you can learn other techniques, like paddling without hand.
I was wrong.
Seems like breaststroke is cycling with auxiliary wheel, and freestyle
without it.
The first 50 meters is hard.
Sometimes the water get into my nose when taking breath, sometimes my head not
high enough to take a breath, most of the times I lose my breath.


_Time_

Swimming tournament is a race against time.
The winner is the fastest one.

The gold medal for men's 50m freestyle
https://en.wikipedia.org/wiki/Swimming_at_the_2019_Southeast_Asian_Games[in SEA Games 2019^]
is 22.62 seconds.
https://olympics.com/en/olympic-games/tokyo-2020/results/swimming/men-s-50m-freestyle[In Olympic 2020^],
the last men finish 50m freestyle is at 21.790 seconds.
From the perspective of the first winner of SEA games, the 0.83 seconds is a
huge gap.
That just the last men, the gap with Olympic gold medal is ~1.55 seconds.

There is no way that I can reach that record in my life time, not even close
to 30 seconds.
I know my body, my ages, and my limit.
I have not done timing myself during 50m freestyle, yet, let just say that
it take around 100 seconds (probably more because its feels so long to me).
Let say I want to make it 90 seconds or 10 seconds faster than my current
time, what I should I do?
I need a lot of practices, I need to invest my time.
Instead of once a week, now I maybe need two or three times a week.
Instead of one hour or less, I should spend more.


_Your opponent is yourself._

Since I am practicing alone, the only opponent that I can beat is myself.

Once I reach the end of the pool, I re-evaluate my practice, what mistakes did
I made, how can I improve it.
After taking couple minutes of break, I try again, re-evaluate again, and
try again.
I keep this practice twice a week.
Finally, I can reach 50m without stopping, but I am still lose my breath at
the end.

Continuously improve to be better, not faster.
By knowing the right technique and a lot of practices, maybe one day I can
finish it in 99 seconds, and then 98 seconds, and finally 90 seconds.
There is no magic or formula to be better at one technique except by learning
from your own mistake and improve it.

Six months after it, with two times practice a week, one hour each, I am still
not able to swim back and forth.
I know that if I keep practice and learning, I will be able to do it.
