name: www-kilabit
type: 'golang:1.17'
hooks:
  build: |
    go generate
    go build ./cmd/www-kilabit
web:
  upstream: 
    socket_family: "tcp"
    protocol: "http"
  commands: 
    start: "./www-kilabit -env=platform.sh"
  locations: 
    '/': 
      allow: false
      passthru: true
