
=== 2024

link:/journal/2024/two_types_of_leader/[Two types of leader^].

link:/journal/2024/bad_coding_practices/[Bad coding practices^].
This journal collect the bad coding practices that I have found during my
journey maintaining legacy software.

link:/journal/2024/new_company/[Peculiar engineering at new company^].
Notes on software engineering or IT in general at new company.
This notes is intended for a reflection of me not to criticize my team
or company.

link:/ama/[Ask Me Anything]. A light version of question and answers related
to my history and backgrounds as software engineer.

link:/journal/2024/karajo_sourcehut_webhook/[karajo: integrating SourceHut
Webhook^].
An article that describe how to integrate
https://sr.ht[SourceHut] with
https://sr.ht/~shulhan/karajo[Karajo].

link:/journal/2024/best_tv_series/[Best TV series^].
List of best non-America TV series that I watched in the past years.

link:/journal/2024/rescached_svcb/[rescached: support on DNS record type
SVCB (64) and HTTPS (65)^]

link:/journal/2024/2023_accomplishment/[2023 accomplishment^].

link:/journal/2024/a_trip_to_nusa_lembongan/[A trip to Nusa
Lembongan^]
