=  Android reverse tether di GNU/Linux
:stylesheet: /assets/style.css

**Skenario:** Anda memiliki koneksi internet di laptop/PC, baik itu
menggunakan LAN atau modem USB, dan ingin menggunakan koneksi tersebut di
smartphone/tablet Android anda.
Berikut diagramnya,

image::https://lh3.googleusercontent.com/Ly5vLOxMEq-f8gMqbD0MNtMlKs8Sk3i1N20vNnfiie09XSKVT1841O2Uhf9HJDR2VsWM7Ne8CVPQh1z4LfIOG3MS7k4b78nmZ7_RpklSaE9-3_ct4BtCckCtFp2QNbjaOqQ2ns8rc6sfgihw6Hjs9JNLd5dgRY1ApbcsxgKO-qdyiE1zOAXjslXeAXTzXBiJq3sRKbyDPCW499h_R9O0nzvF-6kFIWCqFmYc7uJJX9l7NzJvbwuiELidSQiJ8G1ZROkDl5v5HOwEXs9q7ZE2c5-zCM2yl4K-o3O2LG9T-Tc3sGtaOHoZDRaLk2Iw7Uoo_925tw_3_-aJzhmyQc54ZlB5cIyuZQ7pnn5d4VUhSZL8KgGVylmbmRrmg_uC32owdTbYhlMbSUw5sZ-Hx4wKNxVYFm0oGrE7f6UppGEC2S_eB6sZmHuE6dV84KuZamV4PrgiFliUNC-gPa9jxpQKiyDQ4Q0fkly8Zk0i29f4VwCEINGfffpxR2BN3pmbPqZUWRNkC-tA8hoJhhv0-SjtoByaiCsOaPhic9RkpdukdRxS783wStq2u4wyHStJdscBUGrCVuxBgZuHuPxbPu9Bhld8ElVnGiidfhUCjjnP7ftrwM4_PyoV_FWxz7yLzguk8l4I5N5OmqQtPAS9JGNmu7caW-9YQUhNVP4X3UPhOZG8koKr2cb_vF_-KR7L57u88uo5ceSDvbtekQ3G50QbZP4NzvWBkPm6LpC0RKYhlrhlcQjC=w544-h292-no[Reverse
tether in Android]

Solusinya adalah dengan menggunakan metoda reverse tethering, yaitu kebalikan
dari tether.

Pada mode tether, laptop terhubung ke tablet menggunakan WI-FI AP di tablet
dan menggunakan koneksi internet di smartphone/tablet untuk terhubung ke
internet, kebalikannya yaitu mode reverse tether dimana laptop terhubung ke
tablet menggunakan WI-FI AP di tablet tapi tablet menggunakan koneksi internet
di laptop untuk terhubung ke internet.

Untuk contoh implementasi disini perangkatnya adalah laptop dengan OS Linux
yang terkoneksi ke internet lewat USB modem, dan terkoneksi ke tablet Android
menggunakan nirkabel (WI-FI).

Kebutuhan untuk tablet Android adalah,

*  sudah di rooting,
*  memiliki fitur WI-FI Access Pop,
*  sudah terpasang aplikasi terminal seperti Android Terminal Emulator.

Caranya adalah sebagai berikut.

*  Sambungkan laptop ke internet dengan USB modem.
*  Atur supaya laptop dapat meneruskan setiap data dari perangkat jaringan ke
   ppp0 (USB modem) menggunakan perintah iptables di bawah ini,
+
----
iptables -t nat -A POSTROUTING -o ppp0 -j MASQUERADE
iptables -P FORWARD ACCEPT
----

*  Hidupkan WI-FI AP di perangkat tablet Android.
*  Sambungkan WI-FI di laptop supaya terhubung ke WI-FI di tablet Android.
   Catat alamat laptop yang terhubung ke WI-FI tablet, misalnya
   192.168.43.181.
   Alamat ini nanti akan menjadi gateway nantinya bagi tablet Android.
*  Buka terminal di tablet Android, jalankan perintah di bawah sebagai super user (root),
*  Reset IP dari perangkat 3G supaya data tidak terkirim lewat 3G,
+
----
# ifconfig rmnet0 0.0.0.0
----

*  Alihkan koneksi DNS ke publik DNS (8.8.8.8),
+
----
# iptables -t nat -A output -p udp --dport 53 -j DNAT --to-destination 8.8.8.8:53
----

*  Hapus default gateway,
+
----
# ip r del default
----

*  Atur default gateway ke IP di laptop,
+
----
# ip r add default via 192.168.43.181
----

*  Atur DNS ke publik DNS,
+
----
# setprop net.rmnet0.dns1 8.8.8.8
# setprop net.rmnet0.dns2 8.8.4.4
# setprop net.dns1 8.8.8.8
# setprop net.dns2 8.8.4.4
----

Selesai.
Sekarang anda sudah bisa browsing di smartphone/tablet Android anda
menggunakan koneksi internet di laptop.
