=  VirtualBox: Bridge Network

Biasanya, untuk membuat jaringan bridge pada Virtualbox, antara Host dan Guest
tidak perlu pengaturan apapun lagi, karena VirtualBox versi terbaru sudah
otomatis mengaturnya untuk anda.
Tinggal pilih opsi "Bridged Adapter", pilih nama perangkat yang telah
terkoneksi internet yang akan di-bridge sehingga IP beserta gateway-nya akan
otomatis diset sesuai dengan pengaturan pada mesin router.

Gambaran normal koneksi bridge dengan VirtualBox,

----
HOST <== eth0/wlan0 ==> ROUTER <== eth0/wlan0 ==> GUEST

DHCP                                              DHCP
----

Permasalahannya adalah bagaimana jika,

*  anda tidak punya mesin router, atau
*  ingin supaya Host dan Guest tetap saling bisa terkoneksi tapi dengan subnet yang berbeda, atau
*  ingin alamat IP statis pada mesin Guest?

Berikut gambaran pengaturan jaringan yang diinginkan,

----
INTERNET <== ppp0 ==>      HOST      < ETH0 == ?>       GUEST

                      192.168.1.1/24               192.168.1.253/24
----

Diasumsikan, Host terkoneksi ke internet melalui perangkat ppp0 atau wlan0,
sehingga perangkat jaringan yang tersisa, atau yang tidak terpakai, yaitu
eth0.

Untuk itu, saya akan menggunakan eth0 pada Host sebagai gateway yang akan
digunakan oleh Guest untuk dapat saling terkoneksi.
Membuat perangkat baru, tap0, untuk Guest.
Dan menambahkan alamat IP Guest ke tabel routing di mesin Host.

Berikut script untuk konfigurasi VirtualBox dengan bridged network tersendiri, dengan IP statis.

----
#!/bin/sh

ETH=eth0
TAP=tap0
ETHIP=192.168.1.1
TAPIP=192.168.1.253

echo "ETH IP : ${ETHIP}"
echo "TAP IP : ${TAPIP}"

## turn on HOST device

ip link set dev $ETH up

## set HOST device address

ip addr add $ETHIP/24 dev $ETH

## create GUEST device

ip tuntap add dev tap0 mode tap group vboxusers

## set ip-forward on HOST and GUEST devices

echo 1 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv4/conf/$ETH/proxy_arp
echo 1 > /proc/sys/net/ipv4/conf/$TAP/proxy_arp

## turn on GUEST device

ip link set dev $TAP up

## reset GUEST device address

ip addr add 0.0.0.0/24 dev $TAP

## add GUEST IP address to HOST routing table

ip route add $TAPIP dev $TAP
----

Setelah script di atas dijalankan pada pengaturan "VirtualBox > Network", pada
bagian "Attached to" pilih "Bridged Network", dan pada bagian "Name" pilih
"tap0".

Pengaturan jaringan pada Guest yaitu,

----
IP Address : 192.168.1.1
Netmask    : 255.255.255.0
Gateway    : 192.168.1.1
DNS1       : 8.8.8.8
DNS2       : 8.8.4.4
----

Jalankan mesin virtual anda dan Host dan Guest akan terkoneksi, dan Guest juga
masih bisa terhubung ke internet.
