= Gophercon Singapore 2019

I made it!

For GopherCon Singapore 2019 I try to submit two papers.
The first paper is about "Re-learning Slice",

+++
<iframe
	src="https://docs.google.com/presentation/d/e/2PACX-1vTwKUo9uqyMLkJdz5-U9DP6e8Sbx7YFHMSXESwGTN6e5T4qGDcm_nA3qGqhZkUx0x-rEYIE05ZDwpkl/embed?start=false&loop=false&delayms=3000"
	frameborder="0" width="480" height="299" allowfullscreen="true"
	mozallowfullscreen="true" webkitallowfullscreen="true"
></iframe>
+++

and the second paper is about
https://github.com/shuLhan/haminer[haminer: mining HAProxy logs].

+++
<iframe
	src="https://docs.google.com/presentation/d/e/2PACX-1vRusQhz9fx2-Innw4fENdWNLMqSc9HZnLe36QvRmBIdV1hdf0zsgdPu5IMWFPVOsN4BS7vvrFZzOzaf/embed?start=false&loop=false&delayms=3000"
	frameborder="0" width="480" height="299" allowfullscreen="true"
	mozallowfullscreen="true" webkitallowfullscreen="true"
></iframe>
+++

Both are not accepted.
Sad.
But its OK!

My first day of GopherCon is going to workshop at Google Singapore.

.Google Singapore
image::https://lh3.googleusercontent.com/hcHcZqRiuuRWBAT9dutN70CJWyAuvIRODRIZRPzEHgnwAnlwiddS2CMcQ_954IGDE4kYkI-KMvWmkq4P5yIN1IbWWpZCzD88u9Q1aoTPWTduRdpQyoj3t0bsKsL196d69-Zyel4gJl2vrby-bu2cUQZMvWZ2ky7SbL87Y2whNatk8eNGO4PhCNAVig0qVoE0G85TniFEdjbAhKzxmONeffNxHdTAlwIqnN0Q3KQaSmD1zebj_dSCtAW29VVQEGUaDyBRdMOPA2oW3EZrMylwN77HOM1Wk1XNGHMY9muubcnhW_MxMhw3rv5zDSD6MbHpRJ62VPRzAcs9MCaGFE_1mKU3hoSWkfJnudEY_M8LI9ceQjjarHhm_StOQQpIA9satarJ7S_zVq49kB0GfMf0jRiSkH3jDYyU_NiA_w0Va0NgouFsAi_AuRUhcDoKAP9f3Lp2DhIPKWUFeRo0eDPGfYRK0i2kaK0tRZcBI1ZJVOlrF5vWhEup2pZmEr-B-iE-aSgaON-agDKRhvVlcz2gSk9t-6akproJQ2K7bv5FYIGMzLSfbE2cKaPr9lAtWHDPcPjk7GEL8q75R98KnjmOt1f88C-GR_EseoJFE_kr-OMFn3dpazrs3v85Nk3EKmBTOS-iO0VSgKDFZ-dxmgyGh65wCU2OBVPkVVpIEEJD1SR6dE2uWdzZgNFL7Hloic_Qu7XsJ0uu6f7uKP-slLEfrb04xxMuMdrER-Yg0n0nz7e3sLYe=w1232-h320-no[Google
Singapore,800,align="center"]

Actually, this is second day of three days workshop.
I can afford only for single day, so I chose the Dave's session.
The instructor is Mr. Dave "Druid" Cheney ;)
He gave a talk about
https://dave.cheney.net/practical-go/presentations/qcon-china.html[Practical
Go: Real world advice for writing maintainable Go programs], which is
available on his website, for free.
A truly druid.

.Me with Dave `Druid` Cheney
image::https://lh3.googleusercontent.com/RW8AMfFXEv0SxN-eaYTktPC2umC6DTz1-4vVoXZVj6v9VAawu9jzmc1kiYns0ouwds1W0eHXgK32jOWkCYz0rOUZXpCagFwxDqtPHis0cy-aa-Z7pscBNUo0QoRyA6RsuQ4Cyw9L0TYxXGEMnNXvQLEpi2zBwn1Ob20olOpYNiZu9Xz8Vl9Fk1JFqZs2QneNsVAM4plBWslq4N-Q3vS-3eJvteCuHGlo4O09VgBwWjRcB9slTuaTSsttfW32SP6CNRCdk1OWRPwOjsRG9V8e2WSiCfNUV2sjHwUKtIioYuQTiypdLV2PsnfKyJO4lT-uaNoCDL3z1HCPh9raFrjMiw8_fCkY0oWlsbLi4tXrHCldQNqAP982yQcfKIPPQ9yhzfhkNILVT0hvJII5Q_aVPSdOvMr61AVBOzK3aBlvrmusATjmnT77c3qVvGQ2C8iES9dw6FAWSOYzQx1AE5vBInFm9s9shkp6bRDEkxkzEjgnM6BbkdNNfqJ1cPfIBI9sVwwneUq-wXmTaxfPYRxgSrQdzqTrZYSRRHBijSfzsRGRkx5E2SO_ZwTAqgTCgouPwfSaCnI0z7smKqj2hI9990IGupgpPTfzn1ytAVh_V42kRdUqYavlAT7hZLXzxgFE9KYgqMO1j_MBUXg5qJ1FHStlnG_KO0wDEi8YG5Oq6tthPiMqS8l_nzqZTTdpl30qyfftVZCA2TjNHsegYiS5YAdej3RN9miCBYMhUU3TEe8l2qdW=w571-h761-no[Me
with Dave "Druid" Cheney,400,align="center"]

The final day, the conference, is at Marina Bay Sands Expo and Convention
Centre.
There are probably more than 500 gophers attending there,
not only from South East Asia, also from Japan, Austria, and Russia.

.GopherCon Singapore 2019
image::https://lh3.googleusercontent.com/A0jEJppdWyE-CpigWQ7P9QgdSgBtnMQO9Ru7j5PNQX2kdV-Ck3ACLKwxpV0L1QdgygQgAIxaHyEiVFOMQ7xBnX_dnkTlJ3BWXBBBnYiSQkGpup5WWsITrR6Jd5JYEXwJleljde2zbkTkWZmutTvQYCOq68IPAWMLyh7nnIRaWzG4kuhgUfD1NS3qM7xQd1zAmsMCexvDHaattuNfr-osfXnJ2XUyDXDRq9DO18oH5nVNsWuw36w7y37Pf37n79yG_onh2A95pZ-eqwFZIK6xAkewZVMs-lfOkviM311t2p0JBRgA70zyUMBa17a29y5FiIMpcSOjvshXXyHuB2b8v2PlOYtbHqg_4DxpgcfuD_AN4LKsD3D3i6Ao-dFEF5N-MhJcnzHS2VrO64sGCea2unUpOFDOuyusTtj1T0CoX732LO-ygGZGnBY2zJVYl7_OL86ssXvQ8pUD8G0v4bDoGX8-4D6-LB9nyeCE-VBFQWp8Aaqyl2NJifpg8KIKu5REcF4FP-QWeBY0NV87q6FKL7dZAgHnAZ4ihrMu4r4iFiVCGo5QZKkOmRELsdX4a18EJXjsJn9-RMUgQiz545SH-8uXQ_rD5YHXR4SnyIUwHChDUqkP0Di-DlbF6tUJ6Eklm7NnyOUq9ZeEVRSwMvARs-okSHReSh3XOUe2j3xhjQFtRTuV4FbUxxYzaljFZv1fCDrNlrb6f7YDbU9I1EeeH1KnXJVE7XeIWqzmm_PWRIaWYeRk=w1592-h313-no[GopherCon
Singapore 2019,800]

I met so many awesome people there, enthusiastic gophers, and even
people from @ardanlabs and Go team.

Some of the talks I like are from Jacob Walker,
https://www.youtube.com/watch?v=ZMZpH4yT7M0&list=PLq2Nv-Sh8EbYBYteOWx9rNuy0JSF8mzsu&index=4["Understanding
Allocations: the Stack and the Heap"];

.Hi Jacob!
image::https://lh3.googleusercontent.com/5Jx_UWzDM_0_wE9LcdkLBqX83CmrclztZy4tNewXytzwldVYKKHOiMOZmAJcTt4Sl5QsSbY4VA-fvEQfNzH4Ck4ZbGFrdY4eXqCfO9zTAQeKGQ54eHE1NW-_zkz6V4mBH7CdWet9Sximp8fAyuoCz7pU1EolxP2XV9QRn8wX-FKPZYjY-3-9FM4lXaC_0nkynjcu4VwdziSeCBf-QkUunkgFfWoTtWaKwV119OGLBemqviH0YzgA97Cx-Lp2oSSlOAIfr6Neg-pfOaO6Izud73mWVlkY_K-Pu9Q_kfMUHpr_n6VfgHsGEy44rFVNp6mADf2ByfPrlB1fgTSA3sCON7ulqD9gA0-jmOEZwATKWgFpqlHOvjGbz4ttyUoRWUjRPRv1Yzabep4oe_XYUJZx-jXxCtD1_iaaZXz0_fhahWfCqSvuJe9yuinsHuB2YAKbmAU9TOE_NMUyI0F8VR1HLRsL_v-oMkil0hchWk30aPJWEDmZEutws6snqZM6fNyTHvPJMtYc-dEfvsjpIs-4YhubXN44j7OqtFMhQTY_UQU0gNIfygLHRAtJxarWO3DIJA_HY7TUXKg8YLXdAwrWxlG5iWyk8UVh-oThBcA3TOe6eR4Q3BJ7xtuurAPJu1mLlauiKKUz_k7Qac89Dll0oNScAdjPNbm56JE9I1_BRQEc4P5lDgwCmDWHXUH6G9gxigT_7IuGgBVCX_PpUJkLW1xgTWpLuCoWsMvwRggLfkkdAiim=w1015-h761-no[Me
and Jacob Walker from @ardanlabs,400]

Michael Matloob,
https://www.youtube.com/watch?v=HDJE-_s3x8Q&list=PLq2Nv-Sh8EbYBYteOWx9rNuy0JSF8mzsu&index=6["Using
and Writing Go Analyses"];
and from Rebecca Stambler,
https://www.youtube.com/watch?v=gZ7N3HulAb0&list=PLq2Nv-Sh8EbYBYteOWx9rNuy0JSF8mzsu&index=9["Go
pls stop breaking my editor"] (the one who responsible for
https://github.com/golang/go/wiki[gopls]).

.Hi @matloob and @stamblerre!
image::https://lh3.googleusercontent.com/mDsHaFFQFR_wdpzkmumEUImMwd9A8rz4LIO8YTjj5dnbAo6GX0VHSpennt7BeAhPc4xh_pPAYi7dZxj4944kS4Mc-TKWQXAxy_zTpDxVUUgbTI32fu10rMF_2dg4_hPPXWj8yL3a7-DsBYFeFOHeA4ZT9wutqZfj3exiO04XQ8c6do4sLFiQL4pGmjqneVXFUG1uJPHmy9QKoBokHnSK2mJmDjuUfhgWYvfgqX-Wy7eyo9zaru-to3lFmaOiOjYifQoPoWOxEiD1inwweB-ou-jJImjNnQy3apma2JT4_1_lH3OKMQ76-q4rViZ8ISnT8eITeurY6KmdvN7SKob-Zi3gsgCQZ_DJ20561NWAFYoD8QSF9F8fHdKy8WXpjLDx6DO324VaCmS1dDpa2mop8HFfWzD8P3COgoIn_QH0kwM-Mf5ZSQ_m6P__IBii-WmcruOnQVM20MHpBg7-H9WzOVBE9J1QwJhnjbLFMxw6bEBGzYTWuLlhLLhap58Klb25FwSnrty8TnxcjjB3CwGok1pgqZEb4Dxh73xssYCegX9HYN3KMi18GmWIzWNFYkrOXROH_q6uugYyvTCYqiO7ad6NsYnhxzn9ZR84lexvFQxZfJMyIzb6RK2TURazLpnj4bDGAapH_35j1foXJVN8KjJ455Go8Wjc7UArCwfV711wcKSQue20ionzST8ER53PMIPAIwVZPaoCBVxGq3X4TQbVzR--alYdoGpyiGfBYlyifhhM=w1015-h761-no[Me
with @matloob and @stamblerre,400]

All of the talks are available
https://www.youtube.com/watch?v=ftE39xyaJyQ&list=PLq2Nv-Sh8EbYBYteOWx9rNuy0JSF8mzsu[online].

image::https://lh3.googleusercontent.com/EkIklE_e6rjoQKjH186sDL6kmI8fhZecJe1_-0sFgz6uGftFOM6vwOPyQiR7HzIRSBzCPyc2fUF2hV57ADkzWEAhYZ7Y0iJNMzD5GwWs3AzTPSiBCCJe7ASqWMkd0nVIVHCfjTjvY3S6QPBzhu7EFXK61jGCa2eyK5qJKLgOfJsd0WgxSXWKau5JRtZNvJ_EVfkuyQjVYueYDWJZA2ba7jrxP6ECkSSG0NFYC0Nb2UbLV73-Ug7H6H20f3g4lRyWRbNLErEcYkD3FVvCjdlrXHvmCrAXH8SOPqQ6fswXS1g49u9fhj4AnNvjNpaZToGrX0BWYk0_t4Nt0kems2DT80ber-y07lFdcU6D8NmtAy6Uju6qJR96Orp6I135K_OGbmqnlLOlUbdGg6xbWWBhdozxGFZfpIKHCWWQMQqrRD0qcTo8XFJWbnqOwoelsaffb6a6NFAyrfxbNOEAtQq5A7GiZzUnMglZIKTgfZHm0D6iSZ81jLovK35_Mg2DvZszTsbMxfOasBBs3U0K2A7fiXRqwGZ1VfAaXneIZzRibpsF6jie8-iNOFC55ahIsIOyynUCKL6FmXMaQHckWedYNP9sqFovWrdE_zaZ1CUWesfO-t7BPTryDNk9bxC0BrhMrL6NnTj52UoM39UGpP3zo4SzrHkMTXThc0ungD07_h5hmw8XcWjQ9-WJKaCJe-aije3zjU5QgIVv8uo_oZzcwII3YrGHp58IHbfHnxjiWoWnKirn=w1592-h534-no[Singapore,800]

See you next time GopherCon!
