=  Pinky and The Brain
:stylesheet: /assets/style.css

Last Friday, like usual in the middle of jum'at prayer, I am usually listening
to the khotib, but when the talk is rather boring, same content but different
package, I started to think a lot of things.
Yes, a lot of things, usually random thing.
This time I am thinking about how the brain works.

So, lets talk about brain.

In my conscious time my brain think about how exactly the brain works.
How the brain works exactly? is it calculating or memorizing.
This is what I am thinking during that time.

Do you know what is the sum of 9 + 9?
Do you know after adding 1 + 1 + 1 + 1 ... until 18 times or you just know
that the sum is 18?

What about 9 * 9?
What about 10000 * 9876?
The last two question is very simple for the one who graduates from junior
high school.
Maybe.

What about 1234 * 4321?
How many seconds do you need to answer that?
It is the same time when find the answer of 10000 * 9876? or not?

How do you find the answer for 1234 * 4321?
This is one of the solution to find the answer that I has been learned in
school.

----
      1234
      4321
   ------- *
      1234
     2468
    3702
   4936
   ------- +
   5332114
----

We, human that has been in formal education, has been learned to remember
basic thing in school.
The basic thing that can help us to solve the complex thing with a little bit
of work.

I know the result of 4 * 3, 1 * 4, 3 * 3, and 6 + 2 + 2 because I remember it.
But, I did not remember the result of 1234 * 4321.
Why?
Because maybe I think that is useless or I did not want to remember it,
why would I?

And then, how about the "genius", where is it come from?

I, for one, never and never will call some one a genius, smart, stupid or
moron; except for the purpose of a joke :)
I believe that every human has the same brain, the different among peoples it
just that some man do their works with the brain more than the others, in
others word: man that work out their brain.
I prefer to call some one genius with the-man-with-more-experience-than-others
and the stupid one with lazy.

Many of people call that Einstein is genius but I prefer to call him a human
that can memorize _more_ than other people plus he has more experienced than
other in physics and math.
Not because other people cannot memorize like him, but some human brain have a
standard of acceptable thing that they can memorize.
There is a many many reason for that, the simple reason and most reasonable I
can think right now is that some time our brain "reject" what we see and what
we learn.
And why our brain do that, I don't know.
Maybe it was like why we like food A but does not like food B.

After a couple of minute thinking and remembering, I come to conclusion that
our brain is _never_ do any calculating, but what its doing is memorizing.
How stupid of me, sorry, I mean is ... how lazy of me.

Brain: a gift and a curse.
