
Most of my personal projects is open source and available on my
https://github.com/shuLhan[GitHub^]
and
https://sr.ht/~shulhan[SourceHut^]
pages.


===  asciidoctor-go

The asciidoctor-go is the Go module to parse the
https://asciidoctor.org/docs/what-is-asciidoc[AsciiDoc markup^]
and convert it into HTML5.

link:/project/asciidoctor-go/[Project page^]


===  awwan

`awwan` is configuration management software, infrastructure as file and
directory layout.
In other words, `awwan` is command-line interface to execute multiple lines
of command in the local or remote server using SSH.

Do you have a collection of shell scripts to manage one more similar server?
Do you ever want to execute only part of your shell script in remote server?
Are you get tired with learning others syntax and tools for provisioning
your own server, while you need is a handful knowledge of shell script?

If yes, awwan is the right tools for you.

https://awwan.org[Website^] |
https://tour.awwan.org[Tour of awwan^] |
link:/project/awwan/[Project page^]


===  beku (deprecated in favor of Go module)

Beku is command line program to manage packages in user's
environment (GOPATH or vendor directory).
Beku provide syntax like pacman.
This program exists long before before `godep` or Go module exist and stable.

https://github.com/shuLhan/beku[Project page^]


=== ciigo

ciigo is a program to write static web server with embedded files
using asciidoc markup language.
This site and golang-id.org is written with `ciigo` as framework.

link:/project/ciigo/[Project page^]


===  golang-id.org

This website is my second contribution to Go community.
Its goal is not only to provide help, through translation, for Indonesian to
learn more about Go but also to provide an ecosystem for Indonesian Go
community, for example, vlog and blog in Indonesian language, and sharing open
source works written in Go.
The website is freshly launched, they are still more works to be done, though.

https://golang-id.org[Website^] -
https://github.com/golang-id/web[Project page^]


===  gorankusu

`gorankusu` is a Go module that provide HTTP service with web user interface
for testing HTTP endpoints (like Postman) and for load testing.
For the load testing we use
https://github.com/tsenart/vegeta[vegeta^]
as the backend.

link:/project/gorankusu/[Project page^]


===  gotp

Command line interface for Time-based One Time Password (TOTP).

link:/project/gotp/[Project page^]


===  haminer

haminer is a library and program to parse and forward HAProxy logs
to InfluxDB for mining HTTP requests.

link:/project/haminer/[Project page^]


===  hunspell-id

Hunspell dictionary for Bahasa Indonesia.

https://github.com/shuLhan/hunspell-id[Project page^]

===  karajo

karajo is the library and program to implement HTTP workers and manager
similar to AppEngine cron.
karajo has the web user interface for monitoring the jobs.

https://sr.ht/~shulhan/karajo[Project page^]

===  libvos (unmaintained)

libvos is a C++ library.
First implementation was intended for reading and writing Delimited Separated
Value (DSV) data, but then its evolved and have more capabilities.
Current features included Buffer module, File module, Socket module, reading
and writing INI file format, FTP (server and client) module, DNS module, and
Oracle Client Interface module.

https://github.com/shuLhan/libvos[Project page^]


===  pakakeh.go

`pakakeh.go` is collection of Go packages.
The most outstanding packages are WebSocket (server and client), DNS (server
and client), email (client only), STMP, and MemFS (memory file system).

https://sr.ht/~shulhan/pakakeh.go[Project page^]


===  rescached

Rescached is resolver cache daemon.
It is a DNS forwarding server, serve the clients queries, but also caching all
the queries and answers for later use.
The idea is to minimize network traffic for outside DNS queries and to manage
local zone files.
The
https://github.com/shuLhan/rescached-legacy[first implementation^]
was written in C++ and then re-written using Go.

https://sr.ht/~shulhan/rescached[Project page^]

===  tour.golang-id.org

The tour.golang-id.org is translation of their original website
https://go.dev/tour to Indonesian language, to help newcomers learning the
Go programming language.
This is my first contribution to Go community.

https://tour.golang-id.org[Website^] -
https://github.com/golang-id/tour[Project page^]


===  vos (unmaintained)

Vos is a program to process formatted data, i.e. CSV data.
Vos is designed to process a large input file, a file where their size is
larger than the size of memory, and can be tuned to adapt with machine
environment.
Vos can do sorting, formatting, filtering, and join, by reading input file and
its configuration script.
Its written in C.

https://github.com/shuLhan/vos[Project page^]
