=  Mergesort rulez!
:stylesheet: /assets/style.css

==  Analysis of Sorting Algorithm for Large Data

Comparing several sorting algorithm to measure the most efficient algorithm
(in processing time and and speed) for sorting large data, data where their
size is larger than system memory.

Sorting algorithms that I use in this analysis:

*  Merge sort
*  Bucket sort
*  Quick sort
*  Binary sort

Test Machine,

*  cpu: Intel(R) Celeron(R) CPU 550 @ 2.00GHz
*  cache size: 1024 KB
*  RAM size: 512 MB
*  OS: openSUSE 10.3 (default install)

Some notes:

*  Time's includes read/write of data.
*  Input and output data is in csv file format, with 11 columns.


===  Test 1 Sorting Random Data

----
                           +-----------------------------------------------------+
                           | Size of Input Data (* 1,000,000 of record)          |
        +------------------+-----------------------------------------------------+
        |  Sort Algorithm  |   2.5    |    5    |    10    |    15    |    20    |
+-------+------------------+----------+---------+----------+----------+----------+
|       | Merge sort       |   59.37  |  126.16 |  265.05  |  421.84  |  586.44  |
| Times | Binary sort      |   66.58  |  145.03 |  299.72  |  464.23  |  662.62  |
| (sec.)| Bucket sort      |   77.98  |  159.7  |  353.45  |  586.06  |  835.25  |
|       | Quick sort       |   63.31  |  133.99 | 1475.81  | 1858,22  | 2036.56  |
+-------+------------------+----------+---------+----------+----------+----------+
----

image::https://lh3.googleusercontent.com/Uvan8xRWgT60eKSMVSswzXs6_G4QiTMG74Nifx130OsLPBefL0jxyqtngYnDC912Ujcu5cq7u0qIykR33yQz-vgzIBO6wY1PEroO6VKUYzpN2YVskf7ARoxwOiGxzO0uPygkWLzT00LNtYye84g7xbK60HD_0mLfvTA5hWWO69piJXy45pp5yblBBLWVTqil2-e6UZDM-Jj38dgHqsZ9tJjlQRSTV0YsKN5nxLeKbtuMyS7hTk5CJLo1-LkQokGW8IcMkL8jF6J98-TIEx_QdMEqcIGmBBOSdBLeMSztj1ntDCa6mYnfkHC5q_kDJQqSUODsNaA8aqbTlo_f6lhbZXPSrsBwzINkvH8vS02TSWOdOvdZWR1GxDo5I1Ic5cvZhW-cHQhR2osuPYuuJkq9agA-mi7-VvvI9eEPCYEeCeknaVibQgP__3AJndLDWsln2v0LGGHEMZpRUVhFg6gpsT158m1xtNKKZcpzEanXHkLqQf-_jlt31vHvMlPhXTYAF42PtgnIBgPv9vpHyWV-kZdsDXQuBSXTRrBwsMKbu6Yk1_LtZGfXgXuHFWPceviW1Ck2L9n81B41C465HrkzRaUkBsA4gozCSSBTK_AUgp_4G5g7gMbUn0LKITHWY5037JO7F2wzdCU1ki6xzG8frfkXuE6Jgdzthvr4Loeb8WJejQGVETbsxgqoHUmcX6hr3BZ9-FJ7ugCsutWmSzB8T_klwBN1I4rvfc3G0POPnfma6SML=w481-h421-no[Comparison
of sorting algorithm with random data]

===  Test 2 Sorting Ascending Data (data that already sorted)

----
                           +-----------------------------------------------------+
                           | Size of Input Data (* per 1,000,000 of record)      |
        +------------------+-----------------------------------------------------+
        |  Sort Algorithm  |   2.5    |    5    |    10    |    15    |    20    |
+-------+------------------+----------+---------+----------+----------+----------+
|       | Merge sort       |   43.88  |   86.62 |  175.64  |  263.99  |   355.99 |
| Times | Binary sort      |   50.48  |  100.53 |  203.17  |  308.55  |   408.77 |
| (sec.)| Bucket sort      |   64.69  |  129.63 |  256.31  |  390.55  |   501.11 |
|       | Quick sort       |   67.83  |  149.57 | 1839.96  | 9582.04  | 10667.31 |
+-------+------------------+----------+---------+----------+----------+----------+
----

image::https://lh3.googleusercontent.com/Z4EcF4TsbqIflH37cFoMhS6gGBgJ16tVNkjXAwQNTMI3stzuWDuhqamRCQaeNe2YYgjIrOuYd2gZOFxHmyuzfuCFC0Q4ftknswBq-mEGv9YzhJsKhfQ_ZqJTxb5RxBXOmcTsE_DKhDsqsTCkev5ueWNdqC81vGjvKO4qCBQlthcPGZkEvAE-mBa_ad5626oUcdq7he8RwSeUqg2n8chKkTOqF4Twl5T2dNvaaZhUtMKH8xl6Tipnfk_7FO2THWFRbNDHQBD22J8UdajPfhUhhH_27D613Gx2Jf8eKrMglNxatUaXbj9i9DI4Zg5qO1DIZsyzCiurfD3ZdsVWNrXMsnBTh8IXO-TfjdVWkHXMDIhUEPyKcPMfSlyiaPr9oZdrYG9LBP9leVt98WWxYlZNanRR5IYJsbihvj9kcszN6mIjzZlqtJszB6fs7VUnIVjK0kcsk4mkPmbxmtS7NN_E8-7B8AuToR-NQQ9EafOEDn29auSIwGDXFUkuhvuRLPzYu5_z_T7psM0wMfZxMWlT_PA5zBD4rLTBwzdB8IsJWVJuq-JoW94hZLBXYhcV9t9FZ8C4btRLyLc4tf1VnwCQGWespHu6dB9OqrEmmDS6rlALj2xD3o99hV8vCyDHL4xh-jDCTEucm_d1FMbAMY2dq_jMZY6Giylh0c5MdCfHfL0ZYuz2FdY1UqkLL--QTn76Xrogaw0np5dKsAw2y8Bc5ITxGqY45iVOsLPMCGHTaZcGz8lb=w481-h421-no[Sort
comparison ascending order]


===  Test 3: Sorting Descending Data

This benchmark sort data that already sorted in reverse order.

----
                           +-----------------------------------------------------+
                           | Size of Input Data (* 1,000,000 of record)          |
        +------------------+-----------------------------------------------------+
        |  Sort Algorithm  |   2.5    |    5    |    10    |    15    |    20    |
+-------+------------------+----------+---------+----------+----------+----------+
|       | Merge sort       |   44.77  |  89.42  |  177.28  |   275.61 |   366.61 |
| Times | Binary sort      |   50.81  | 100.59  |  202.02  |   307.47 |   405.98 |
| (sec.)| Bucket sort      |   67.83  | 127.37  |  256.24  |   384.67 |   513.96 |
|       | Quick sort       |   68.97  | 151.07  | 6572.53  | 13161.53 | 10335.81 |
+-------+------------------+----------+---------+----------+----------+----------+
----

image::https://lh3.googleusercontent.com/x-nrqiaJoG3vJsDEn362U0s_TuvcnaGnmfu4NfNvMeZrZXMp424Ptlnly0-G1K_0wSElRGmX_BbcMpZpOYAXoukU24Zag146Enf5JWaUUgK1upQNZvUPVYaUUKMuJ-lj6bTzw5KuFIEY8vUckAA-0WO-9Arc4C2dPtIxRVZ5CrGCU9VvwNUtma3scMWy2qyRm02iW3lzJSitqoS8B01dT5YghLWUvp-YulsDV1E7iozgx8L2ZjJHSipt2vqdOcS_lr4wmkG37U6W1N5JXknwy1sIrLk7fwhhziOuQV9AwEsp6yB8XkzmlQQ_4cMuwbaHuAoEqrJiAahMME-QmoNd7SfwL-1_F-l7nxjWcgF-QnUIJqMlAs3uLsOC-ZLyJ1w9HVRoH7PTGFZhyzK7EuO-VLYlh5F5ebHTVDWjIOc4HLeBzwBkxBsEM2QVu6UL1roWhij33qY2idKwviLHnPUhP05tGhvj5Lih_A8tEMVCDp3d6bD-Fx5uBjq51NmOYYeZKQbcRj2FGTznprt_Ux6_Suf02sFUNBB4gATognWhHD_ZCPfhYv5KBueeeLa4QjtHnVzeg7_mmH8F415METcNIxZUgaqQdkCGXfn-_-nizVLN8yvZtubSkkJug_fGff1IbSmKeYcQWt09LIHqHW_eZQNhnaC5QTTZ3dhmsc0tBNxXzic7ZZGFJlf4A09y90Buvs_NvUFjb1fLkUVRQ8JaNO6gdMcgOp_U1WAyj3xdgyS8-OWL=w481-h421-no[Comparison
of sorting algorithm with descended data]
